FROM python:3.6-alpine
RUN apk add --update build-base libffi-dev
RUN apk add --update postgresql-dev
RUN pip install gunicorn
RUN pip install google-python-cloud-debugger
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
ADD . /code
WORKDIR /code
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 boot:app
